export const dataProjects = [
    {
        title: "Projeto de cartão de blog minimalista",
        level: "Novato",
        link: "/challenge/minimal-blog-card",
        img: "https://devchallenges.io/_next/image?url=https%3A%2F%2Fcsyxkpbavpcrhwqhcpyy.supabase.co%2Fstorage%2Fv1%2Fobject%2Fpublic%2Fchallenges%2F27%2Fchallenge-27-thumbnail&w=640&q=75",
        description: "Este desafio é uma ótima maneira de começar com habilidades básicas de HTML e CSS.",
        section: 1,
    },
    {
        title: "Projeto de cartão de blog de negócios",
        level: "Novato",
        link: "/challenge/business-blog-card",
        img: "https://devchallenges.io/_next/image?url=https%3A%2F%2Fcsyxkpbavpcrhwqhcpyy.supabase.co%2Fstorage%2Fv1%2Fobject%2Fpublic%2Fchallenges%2F28%2Fchallenge-28-thumbnail&w=640&q=75",
        description: "Este desafio é uma ótima maneira de praticar habilidades básicas de HTML e CSS.",
        section: 1,
    },
    {
        title: "Projeto Página de Depoimentos",
        level: "Novato",
        link: "/challenge/reviewers-page",
        img: "https://devchallenges.io/_next/image?url=https%3A%2F%2Fcsyxkpbavpcrhwqhcpyy.supabase.co%2Fstorage%2Fv1%2Fobject%2Fpublic%2Fchallenges%2F29%2Fchallenge-29-thumbnail&w=640&q=75",
        description: "Este desafio é praticar habilidades mais avançadas de HTML e CSS.",
        section: 1,
    },
    {
        title: "Projeto de página de processo",
        level: "Novato",
        link: "/challenge/process-page",
        img: "https://devchallenges.io/_next/image?url=https%3A%2F%2Fcsyxkpbavpcrhwqhcpyy.supabase.co%2Fstorage%2Fv1%2Fobject%2Fpublic%2Fchallenges%2F30%2Fchallenge-30-thumbnail&w=640&q=75",
        description: "Este desafio é praticar design responsivo com habilidades em HTML e CSS.",
        section: 1,
    },
    {
        title: "Projeto de página de contato",
        level: "Novato",
        link: "/challenge/contact-page",
        img: "https://devchallenges.io/_next/image?url=https%3A%2F%2Fcsyxkpbavpcrhwqhcpyy.supabase.co%2Fstorage%2Fv1%2Fobject%2Fpublic%2Fchallenges%2F31%2Fchallenge-31-thumbnail&w=640&q=75",
        description: "Este desafio é praticar design responsivo e de formulário com habilidades em HTML e CSS.",
        section: 1,
    },
    {
        title: "Projeto da página de perguntas frequentes",
        level: "Novato",
        link: "/challenge/faq-page",
        img: "https://devchallenges.io/_next/image?url=https%3A%2F%2Fcsyxkpbavpcrhwqhcpyy.supabase.co%2Fstorage%2Fv1%2Fobject%2Fpublic%2Fchallenges%2F32%2Fchallenge-32-thumbnail&w=640&q=75",
        description: "Este desafio é uma ótima maneira de começar a usar JS com HTML e CSS.",
        section: 1,
    },
    {
        title: "Página inicial simples - Projeto Alarado",
        level: "Novato",
        link: "/challenge/simple-homepage-alarado",
        img: "https://devchallenges.io/_next/image?url=https%3A%2F%2Fcsyxkpbavpcrhwqhcpyy.supabase.co%2Fstorage%2Fv1%2Fobject%2Fpublic%2Fchallenges%2F33%2Fchallenge-33-thumbnail&w=640&q=75",
        description: "Este desafio é uma ótima maneira de começar a usar JS com HTML e CSS.",
        section: 1,
    },
    {
        title: "Página inicial avançada - Projeto Hufie",
        level: "Júnior",
        link: "/challenge/advanced-homepage-hufie",
        img: "https://devchallenges.io/_next/image?url=https%3A%2F%2Fcsyxkpbavpcrhwqhcpyy.supabase.co%2Fstorage%2Fv1%2Fobject%2Fpublic%2Fchallenges%2F33%2Fchallenge-33-thumbnail&w=640&q=75",
        description: "Este desafio colocará suas habilidades em HTML e CSS à prova.",
        section: 1,
    },
    {
        title: "Projeto Perguntas Frequentes Simples (FAQ)",
        level: "Novato",
        link: "/challenge/simple-faq",
        img: "https://devchallenges.io/_next/image?url=https%3A%2F%2Fcsyxkpbavpcrhwqhcpyy.supabase.co%2Fstorage%2Fv1%2Fobject%2Fpublic%2Fchallenges%2F33%2Fchallenge-33-thumbnail&w=640&q=75",
        description: "Crie uma página de FAQ simples para testar a sintaxe HTML e CSS.",
        section: 1,
    },
    {
        title: "Participe do nosso projeto de Newsletter",
        level: "Novato",
        link: "/challenge/newsletter-project",
        img: "https://devchallenges.io/_next/image?url=https%3A%2F%2Fcsyxkpbavpcrhwqhcpyy.supabase.co%2Fstorage%2Fv1%2Fobject%2Fpublic%2Fchallenges%2F33%2Fchallenge-33-thumbnail&w=640&q=75",
        description: "Participe do desafio do nosso boletim informativo com HTML e CSS.",
        section: 1,
    },
    {
        title: "Projeto de Listagem de Artigos Simples",
        level: "Novato",
        link: "/challenge/article-listing",
        img: "https://devchallenges.io/_next/image?url=https%3A%2F%2Fcsyxkpbavpcrhwqhcpyy.supabase.co%2Fstorage%2Fv1%2Fobject%2Fpublic%2Fchallenges%2F64%2Fchallenge-64-thumbnail&w=640&q=75",
        description: "Crie um desafio simples de listagem de artigos com HTML e CSS.",
        section: 1,
    },
    {
        title: "Projeto de seção de recursos simples",
        level: "Novato",
        link: "/challenge/feature-section",
        img: "https://devchallenges.io/_next/image?url=https%3A%2F%2Fcsyxkpbavpcrhwqhcpyy.supabase.co%2Fstorage%2Fv1%2Fobject%2Fpublic%2Fchallenges%2F65%2Fchallenge-65-thumbnail&w=640&q=75",
        description: "Programe um desafio de seção de recursos simples com HTML e CSS.",
        section: 1,
    },
    {
        title: "Projeto de página de produto simples",
        level: "Júnior",
        link: "/challenge/simple-product-page",
        img: "https://devchallenges.io/_next/image?url=https%3A%2F%2Fcsyxkpbavpcrhwqhcpyy.supabase.co%2Fstorage%2Fv1%2Fobject%2Fpublic%2Fchallenges%2F66%2Fchallenge-66-thumbnail&w=640&q=75",
        description: "Programe um desafio simples de página de produto com HTML e CSS.",
        section: 1,
    },
    {
        title: "Página inicial simples - Projeto Echoplex",
        level: "Júnior",
        link: "/challenge/simple-homepage-echoplex",
        img: "https://devchallenges.io/_next/image?url=https%3A%2F%2Fcsyxkpbavpcrhwqhcpyy.supabase.co%2Fstorage%2Fv1%2Fobject%2Fpublic%2Fchallenges%2F67%2Fchallenge-67-thumbnail&w=640&q=75",
        description: "Crie um pequeno desafio de site com HTML e CSS para praticar o uso de layout de 12 grades.",
        section: 1,
    },
    {
        title: "Projeto de seção de recursos de layout de caixa Bento",
        level: "Júnior",
        link: "/challenge/bento-layout",
        img: "https://devchallenges.io/_next/image?url=https%3A%2F%2Fcsyxkpbavpcrhwqhcpyy.supabase.co%2Fstorage%2Fv1%2Fobject%2Fpublic%2Fchallenges%2F68%2Fchallenge-68-thumbnail&w=640&q=75",
        description: "Crie um desafio de site com layout de caixa de bento com HTML e CSS.",
        section: 1,
    },
    {
        title: "Conheça a equipe do projeto Section",
        level: "Júnior",
        link: "/challenge/team-section",
        img: "https://devchallenges.io/_next/image?url=https%3A%2F%2Fcsyxkpbavpcrhwqhcpyy.supabase.co%2Fstorage%2Fv1%2Fobject%2Fpublic%2Fchallenges%2F69%2Fchallenge-69-thumbnail&w=640&q=75",
        description: "Crie um desafio de site de seção meet the team com design fornecido.",
        section: 1,
    },
    {
        title: "Projeto Tabela de Preços",
        level: "Júnior",
        link: "/challenge/pricing-table",
        img: "https://devchallenges.io/_next/image?url=https%3A%2F%2Fcsyxkpbavpcrhwqhcpyy.supabase.co%2Fstorage%2Fv1%2Fobject%2Fpublic%2Fchallenges%2F70%2Fchallenge-70-thumbnail&w=640&q=75",
        description: "Crie um desafio de site de seção de tabela de preços com design fornecido.",
        section: 1,
    },
    {
        title: "Painel do Banco - Projeto HBank",
        level: "Nível médio",
        link: "/challenge/bank-dashboard",
        img: "https://devchallenges.io/_next/image?url=https%3A%2F%2Fcsyxkpbavpcrhwqhcpyy.supabase.co%2Fstorage%2Fv1%2Fobject%2Fpublic%2Fchallenges%2F71%2Fchallenge-71-thumbnail&w=640&q=75",
        description: "Crie um desafio de site de painel de banco com design fornecido.",
        section: 1,
    },
    {
        title: "Projeto de checkout da Device Shop",
        level: "Júnior",
        link: "/challenge/device-shop-checkout",
        img: "https://devchallenges.io/_next/image?url=https%3A%2F%2Fcsyxkpbavpcrhwqhcpyy.supabase.co%2Fstorage%2Fv1%2Fobject%2Fpublic%2Fchallenges%2F72%2Fchallenge-72-thumbnail&w=640&q=75",
        description: "Crie um desafio de site de checkout da Apple Store com o design fornecido.",
        section: 1,
    },
    {
        title: "Projeto de checkout de assinatura",
        level: "Júnior",
        link: "/challenge/subscription-checkout",
        img: "https://devchallenges.io/_next/image?url=https%3A%2F%2Fcsyxkpbavpcrhwqhcpyy.supabase.co%2Fstorage%2Fv1%2Fobject%2Fpublic%2Fchallenges%2F73%2Fchallenge-73-thumbnail&w=640&q=75",
        description: "Crie um desafio de site de página de checkout de assinatura com o design fornecido.",
        section: 1,
    },
    {
        title: "Projeto gerador de código QR",
        level: "Júnior",
        link: "/challenge/qr-code-generator",
        img: "https://devchallenges.io/_next/image?url=https%3A%2F%2Fcsyxkpbavpcrhwqhcpyy.supabase.co%2Fstorage%2Fv1%2Fobject%2Fpublic%2Fchallenges%2F35%2Fchallenge-35-thumbnail&w=640&q=75",
        description: "Este projeto oferece uma excelente oportunidade para praticar suas habilidades em JavaScript criando um gerador de QR Code.",
        section: 2,
    },
    {
        title: "Projeto de citação aleatória",
        level: "Júnior",
        link: "/challenge/random-quote-generator",
        img: "https://devchallenges.io/_next/image?url=https%3A%2F%2Fcsyxkpbavpcrhwqhcpyy.supabase.co%2Fstorage%2Fv1%2Fobject%2Fpublic%2Fchallenges%2F36%2Fchallenge-36-thumbnail&w=640&q=75",
        description: "Este desafio é uma excelente oportunidade para ganhar experiência prática na utilização de APIs externas com JavaScript.",
        section: 2,
    },
    {
        title: "Projeto básico de conversão de texto em fala",
        level: "Nível médio",
        link: "/challenge/text-to-speech",
        img: "https://devchallenges.io/_next/image?url=https%3A%2F%2Fcsyxkpbavpcrhwqhcpyy.supabase.co%2Fstorage%2Fv1%2Fobject%2Fpublic%2Fchallenges%2F37%2Fchallenge-37-thumbnail&w=640&q=75",
        description: "O projeto é criar um aplicativo simples de conversão de texto em fala usando funções JavaScript avançadas integradas.",
        section: 2,
    },
    {
        title: "Projeto do aplicativo de busca de filmes",
        level: "Nível médio",
        link: "/challenge/movie-info-search",
        img: "https://devchallenges.io/_next/image?url=https%3A%2F%2Fcsyxkpbavpcrhwqhcpyy.supabase.co%2Fstorage%2Fv1%2Fobject%2Fpublic%2Fchallenges%2F38%2Fchallenge-38-thumbnail&w=640&q=75",
        description: "O projeto é criar um aplicativo de busca de filmes usando APIs externas e funções JavaScript avançadas.",
        section: 2,
    },
    {
        title: "Projeto de formulário de registro em várias etapas",
        level: "Júnior",
        link: "/challenge/multi-step-form",
        img: "https://devchallenges.io/_next/image?url=https%3A%2F%2Fcsyxkpbavpcrhwqhcpyy.supabase.co%2Fstorage%2Fv1%2Fobject%2Fpublic%2Fchallenges%2F39%2Fchallenge-39-thumbnail&w=640&q=75",
        description: "Este desafio oferece uma ótima oportunidade para aprimorar suas habilidades em JavaScript criando um registro de 3 etapas.",
        section: 2,
    },
    {
        title: "Projeto Music Player",
        level: "Júnior",
        link: "/challenge/music-player",
        img: "https://devchallenges.io/_next/image?url=https%3A%2F%2Fcsyxkpbavpcrhwqhcpyy.supabase.co%2Fstorage%2Fv1%2Fobject%2Fpublic%2Fchallenges%2F40%2Fchallenge-40-thumbnail&w=640&q=75",
        description: "Este projeto é uma excelente oportunidade para aprimorar suas habilidades em JavaScript criando um music player simples.",
        section: 2,
    },
    {
        title: "Projeto Adivinhe a Palavra",
        level: "Nível médio",
        link: "/challenge/guess-the-word",
        img: "https://devchallenges.io/_next/image?url=https%3A%2F%2Fcsyxkpbavpcrhwqhcpyy.supabase.co%2Fstorage%2Fv1%2Fobject%2Fpublic%2Fchallenges%2F41%2Fchallenge-41-thumbnail&w=640&q=75",
        description: "Este projeto é ótimo para avançar suas habilidades em JavaScript. O projeto é criar um pequeno jogo que desafia o usuário a adivinhar palavras.",
        section: 2,
    },
    {
        title: "Projeto de perfil do GitHub",
        level: "Nível médio",
        link: "/challenge/github-profile",
        img: "https://devchallenges.io/_next/image?url=https%3A%2F%2Fcsyxkpbavpcrhwqhcpyy.supabase.co%2Fstorage%2Fv1%2Fobject%2Fpublic%2Fchallenges%2F42%2Fchallenge-42-thumbnail&w=640&q=75",
        description: "O projeto requer a criação de um aplicativo de pesquisa de perfil do Github que utiliza vários pontos de extremidade de API.",
        section: 3,
    },
    {
        title: "Projeto de Listagem Simples de Café",
        level: "Júnior",
        link: "/challenge/simple-coffee-listing",
        img: "https://devchallenges.io/_next/image?url=https%3A%2F%2Fcsyxkpbavpcrhwqhcpyy.supabase.co%2Fstorage%2Fv1%2Fobject%2Fpublic%2Fchallenges%2F42%2Fchallenge-42-thumbnail&w=640&q=75",
        description: "Este projeto é ótimo para trabalhar com bibliotecas front-end como React, Vue...",
        section: 3,
    },
    {
        title: "Projeto de Listagem de Imóveis",
        level: "Nível médio",
        link: "/challenge/property-listing",
        img: "https://devchallenges.io/_next/image?url=https%3A%2F%2Fcsyxkpbavpcrhwqhcpyy.supabase.co%2Fstorage%2Fv1%2Fobject%2Fpublic%2Fchallenges%2F42%2Fchallenge-42-thumbnail&w=640&q=75",
        description: "Este projeto é perfeito para melhorar suas habilidades de Frontend do iniciante ao mais avançado.",
        section: 3,
    },
    {
        title: "Projeto de aplicativo de tradução",
        level: "Nível médio",
        link: "/challenge/translate-app",
        img: "https://devchallenges.io/_next/image?url=https%3A%2F%2Fcsyxkpbavpcrhwqhcpyy.supabase.co%2Fstorage%2Fv1%2Fobject%2Fpublic%2Fchallenges%2F47%2Fchallenge-47-thumbnail&w=640&q=75",
        description: "Como desenvolvedor Frontend, você receberá tarefas para construir um aplicativo interativo.",
        section: 3,
    },
    {
        title: "Página de receitas - Projeto HomeChef",
        level: "Nível médio",
        link: "/challenge/homechef-recipe",
        img: "https://devchallenges.io/_next/image?url=https%3A%2F%2Fcsyxkpbavpcrhwqhcpyy.supabase.co%2Fstorage%2Fv1%2Fobject%2Fpublic%2Fchallenges%2F48%2Fchallenge-48-thumbnail&w=640&q=75",
        description: "Neste desafio, você trabalhará com uma API para construir uma Página/Aplicativo de Receita.",
        section: 3,
    },
    {
        title: "Página do país - Projeto WorldRanks",
        level: "Nível médio",
        link: "/challenge/worldranks",
        img: "https://devchallenges.io/_next/image?url=https%3A%2F%2Fcsyxkpbavpcrhwqhcpyy.supabase.co%2Fstorage%2Fv1%2Fobject%2Fpublic%2Fchallenges%2F49%2Fchallenge-49-thumbnail&w=640&q=75",
        description: "Muitas vezes, como desenvolvedor, você terá que trabalhar com uma quantidade maior de dados.",
        section: 3,
    },
    {
        title: "Projeto Quiz do País",
        level: "Nível médio",
        link: "/challenge/country-quiz",
        img: "https://devchallenges.io/_next/image?url=https%3A%2F%2Fcsyxkpbavpcrhwqhcpyy.supabase.co%2Fstorage%2Fv1%2Fobject%2Fpublic%2Fchallenges%2F50%2Fchallenge-50-thumbnail&w=640&q=75",
        description: "Na maioria das vezes, a API é otimizada para exibir um conjunto de dados, mas outras vezes, precisamos modificar...",
        section: 3,
    },
    {
        title: "Chatbot de IA - projeto simplechat.ai",
        level: "Nível médio",
        link: "/challenge/simplechat-ai",
        img: "https://devchallenges.io/_next/image?url=https%3A%2F%2Fcsyxkpbavpcrhwqhcpyy.supabase.co%2Fstorage%2Fv1%2Fobject%2Fpublic%2Fchallenges%2F51%2Fchallenge-51-thumbnail&w=640&q=75",
        description: "Como a IA é o futuro, saber como construir um chatbot de IA pode ser útil.",
        section: 3,
    },
    {
        title: "Projeto do aplicativo do tempo",
        level: "Médio-alto",
        link: "/challenge/weather-app",
        img: "https://devchallenges.io/_next/image?url=https%3A%2F%2Fcsyxkpbavpcrhwqhcpyy.supabase.co%2Fstorage%2Fv1%2Fobject%2Fpublic%2Fchallenges%2F52%2Fchallenge-52-thumbnail&w=640&q=75",
        description: "O aplicativo Weather tem sido um projeto popular para adicionar aos portfólios de muitos desenvolvedores.",
        section: 3,
    },
    {
        title: "Projeto do aplicativo Gerenciador de Tarefas",
        level: "Médio-alto",
        link: "/challenge/task-manager-app",
        img: "https://devchallenges.io/_next/image?url=https%3A%2F%2Fcsyxkpbavpcrhwqhcpyy.supabase.co%2Fstorage%2Fv1%2Fobject%2Fpublic%2Fchallenges%2F54%2Fchallenge-54-thumbnail&w=640&q=75",
        description: "Neste desafio full-stack, você desenvolverá um aplicativo de gerenciamento de tarefas simples.",
        section: 3,
    },
];