export const dataSkills = [
  {
    name: "HTML5",
    description: "Cada parte do conteúdo de uma página da web é encapsulada em elementos HTML",
    link: "/learn/2-responsive-web/introduction-to-html-and-css",
    icon: "/logos/html5.svg",
    section: 1,
  },
  {
    name: "CSS3",
    description: "CSS descreve como os elementos HTML devem ser exibidos",
    link: "/learn/2-responsive-web/css-essential-cheat-sheet",
    icon: "/logos/css3.svg",
    section: 1,
  },
  {
    name: "TailwindCSS",
    description: "Uma estrutura CSS voltada para utilidade para desenvolvimento rápido de UI",
    link: "https://tailwindcss.com/",
    icon: "/logos/tailwind.svg",
    section: 1,
  },
  {
    name: "JavaScript",
    description: "JavaScript é a linguagem de programação da Web",
    link: "/learn/3-javascript/introduction-to-javascript",
    icon: "/logos/javascript.svg",
    section: 1,
  },
  {
    name: "Git",
    description: "Git é um sistema de controle de versão distribuído para rastrear alterações no código-fonte",
    link: "/learn/1-fundamentals/introduction-to-git-and-github",
    icon: "/logos/git.svg",
    section: 1,
  },
  {
    name: "JavaScript",
    description: "JavaScript é a linguagem de programação da Web.",
    link: "/learn/3-javascript/introduction-to-javascript",
    icon: "/logos/javascript.svg",
    section: 2,
  },
  {
    name: "TypeScript",
    description: "TypeScript é um superconjunto tipado de JavaScript que é compilado para JavaScript simples.",
    link: "/learn/3-javascript/introduction-to-typescript",
    icon: "/logos/typescript.svg",
    section: 2,
  },
  {
    name: "HTML5",
    description: "Cada parte do conteúdo de uma página da web é encapsulada em elementos HTML.",
    link: "/learn/2-responsive-web/introduction-to-html-and-css",
    icon: "/logos/html5.svg",
    section: 2,
  },
  {
    name: "CSS3",
    description: "CSS descreve como os elementos HTML devem ser exibidos.",
    link: "/learn/2-responsive-web/css-essential-cheat-sheet",
    icon: "/logos/css3.svg",
    section: 2,
  },
  {
    name: "Git",
    description: "Git é um sistema de controle de versão distribuído para rastrear alterações no código-fonte durante o desenvolvimento de software.",
    link: "/learn/1-fundamentals/introduction-to-git-and-github",
    icon: "/logos/git.svg",
    section: 2,
  },
  {
    name: "React",
    description: "React é a biblioteca front-end mais popular para criar interfaces de usuário.",
    link: "/learn/react",
    icon: "/logos/react.svg",
    section: 3,
  },
  {
    name: "Next.js",
    description: "Next.js é um framework React que permite funcionalidades como renderização do lado do servidor e geração de sites estáticos para aplicativos web baseados em React.",
    link: "/learn/nextjs",
    icon: "/logos/nextjs.svg",
    section: 3,
  },
  {
    name: "Vue.js",
    description: "Vue.js é um framework JavaScript progressivo para construção de interfaces de usuário.",
    link: "/learn/vue",
    icon: "/logos/vue.svg",
    section: 3,
  },
  {
    name: "Svelte",
    description: "Svelte é uma nova abordagem radical para criar interfaces de usuário.",
    link: "/learn/svelte",
    icon: "/logos/svelte.svg",
    section: 3,
  },
  {
    name: "JavaScript",
    description: "JavaScript é a linguagem de programação da Web.",
    link: "/learn/javascript",
    icon: "/logos/javascript.svg",
    section: 3,
  },
  {
    name: "TypeScript",
    description: "TypeScript é um superconjunto tipado de JavaScript que é compilado para JavaScript simples.",
    link: "/learn/typescript",
    icon: "/logos/typescript.svg",
    section: 3,
  },
  {
    name: "Jest",
    description: "Jest é um framework de testes JavaScript muito agradável com foco na simplicidade.",
    link: "/learn/jest",
    icon: "/logos/jest.svg",
    section: 3,
  },
  {
    name: "HTML5",
    description: "Cada parte do conteúdo de uma página da web é encapsulada em elementos HTML.",
    link: "/learn/html5",
    icon: "/logos/html5.svg",
    section: 3,
  },
  {
    name: "CSS3",
    description: "CSS descreve como os elementos HTML devem ser exibidos.",
    link: "/learn/css3",
    icon: "/logos/css3.svg",
    section: 3,
  },
  {
    name: "Git",
    description: "Git é um sistema de controle de versão distribuído para rastrear alterações no código-fonte durante o desenvolvimento de software.",
    link: "/learn/git",
    icon: "/logos/git.svg",
    section: 3,
  },
  {
    name: "Tailwind CSS",
    description: "Uma estrutura CSS voltada para utilitários para desenvolvimento rápido de interfaces de usuário.",
    link: "/learn/tailwindcss",
    icon: "/logos/tailwind.svg",
    section: 3,
  },
];